# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='CountryMessages.proto',
  package='messages',
  serialized_pb='\n\x15\x43ountryMessages.proto\x12\x08messages\":\n\x07\x43ountry\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tshortName\x18\x02 \x01(\t\x12\x10\n\x08longName\x18\x03 \x01(\t\"\xba\x01\n\x11\x43ountryGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tstartTime\x18\x02 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\x04\x12\x11\n\tstartDate\x18\x04 \x01(\x04\x12\x0f\n\x07\x65ndDate\x18\x05 \x01(\x04\x12#\n\x08\x63riteria\x18\x06 \x01(\x0b\x32\x11.messages.Country\x12\x15\n\rtransactionId\x18\x07 \x01(\t\x12\x15\n\rinitDependent\x18\x08 \x01(\x08\"I\n\x12\x43ountryGetResponse\x12!\n\x06values\x18\x08 \x03(\x0b\x32\x11.messages.Country\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"9\n\x14\x43ountryRemoveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"5\n\x15\x43ountryRemoveResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"N\n\x13\x43ountryStoreRequest\x12 \n\x05value\x18\x01 \x02(\x0b\x32\x11.messages.Country\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"4\n\x14\x43ountryStoreResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB \n\x1eru.nicetu.integration.messages')




_COUNTRY = descriptor.Descriptor(
  name='Country',
  full_name='messages.Country',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.Country.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shortName', full_name='messages.Country.shortName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='longName', full_name='messages.Country.longName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=35,
  serialized_end=93,
)


_COUNTRYGETREQUEST = descriptor.Descriptor(
  name='CountryGetRequest',
  full_name='messages.CountryGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.CountryGetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='messages.CountryGetRequest.startTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='messages.CountryGetRequest.endTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startDate', full_name='messages.CountryGetRequest.startDate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endDate', full_name='messages.CountryGetRequest.endDate', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='criteria', full_name='messages.CountryGetRequest.criteria', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.CountryGetRequest.transactionId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initDependent', full_name='messages.CountryGetRequest.initDependent', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=96,
  serialized_end=282,
)


_COUNTRYGETRESPONSE = descriptor.Descriptor(
  name='CountryGetResponse',
  full_name='messages.CountryGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='messages.CountryGetResponse.values', index=0,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.CountryGetResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=284,
  serialized_end=357,
)


_COUNTRYREMOVEREQUEST = descriptor.Descriptor(
  name='CountryRemoveRequest',
  full_name='messages.CountryRemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.CountryRemoveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.CountryRemoveRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=359,
  serialized_end=416,
)


_COUNTRYREMOVERESPONSE = descriptor.Descriptor(
  name='CountryRemoveResponse',
  full_name='messages.CountryRemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.CountryRemoveResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.CountryRemoveResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=418,
  serialized_end=471,
)


_COUNTRYSTOREREQUEST = descriptor.Descriptor(
  name='CountryStoreRequest',
  full_name='messages.CountryStoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.CountryStoreRequest.value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.CountryStoreRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=473,
  serialized_end=551,
)


_COUNTRYSTORERESPONSE = descriptor.Descriptor(
  name='CountryStoreResponse',
  full_name='messages.CountryStoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.CountryStoreResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.CountryStoreResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=553,
  serialized_end=605,
)

_COUNTRYGETREQUEST.fields_by_name['criteria'].message_type = _COUNTRY
_COUNTRYGETRESPONSE.fields_by_name['values'].message_type = _COUNTRY
_COUNTRYSTOREREQUEST.fields_by_name['value'].message_type = _COUNTRY
DESCRIPTOR.message_types_by_name['Country'] = _COUNTRY
DESCRIPTOR.message_types_by_name['CountryGetRequest'] = _COUNTRYGETREQUEST
DESCRIPTOR.message_types_by_name['CountryGetResponse'] = _COUNTRYGETRESPONSE
DESCRIPTOR.message_types_by_name['CountryRemoveRequest'] = _COUNTRYREMOVEREQUEST
DESCRIPTOR.message_types_by_name['CountryRemoveResponse'] = _COUNTRYREMOVERESPONSE
DESCRIPTOR.message_types_by_name['CountryStoreRequest'] = _COUNTRYSTOREREQUEST
DESCRIPTOR.message_types_by_name['CountryStoreResponse'] = _COUNTRYSTORERESPONSE

class Country(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTRY
  
  # @@protoc_insertion_point(class_scope:messages.Country)

class CountryGetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTRYGETREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.CountryGetRequest)

class CountryGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTRYGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.CountryGetResponse)

class CountryRemoveRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTRYREMOVEREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.CountryRemoveRequest)

class CountryRemoveResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTRYREMOVERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.CountryRemoveResponse)

class CountryStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTRYSTOREREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.CountryStoreRequest)

class CountryStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COUNTRYSTORERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.CountryStoreResponse)

# @@protoc_insertion_point(module_scope)
