# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='DocumentMessages.proto',
  package='messages',
  serialized_pb='\n\x16\x44ocumentMessages.proto\x12\x08messages\"\x87\x01\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0borderNumber\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\x04\x12\x10\n\x08signedBy\x18\x05 \x01(\t\x12\x0e\n\x06\x63ipher\x18\x06 \x01(\t\x12\r\n\x05image\x18\x07 \x01(\x0c\x12\x0c\n\x04type\x18\x08 \x01(\t\"\xbc\x01\n\x12\x44ocumentGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tstartTime\x18\x02 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\x04\x12\x11\n\tstartDate\x18\x04 \x01(\x04\x12\x0f\n\x07\x65ndDate\x18\x05 \x01(\x04\x12$\n\x08\x63riteria\x18\x06 \x01(\x0b\x32\x12.messages.Document\x12\x15\n\rtransactionId\x18\x07 \x01(\t\x12\x15\n\rinitDependent\x18\x08 \x01(\x08\"K\n\x13\x44ocumentGetResponse\x12\"\n\x06values\x18\x08 \x03(\x0b\x32\x12.messages.Document\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\":\n\x15\x44ocumentRemoveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"6\n\x16\x44ocumentRemoveResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"P\n\x14\x44ocumentStoreRequest\x12!\n\x05value\x18\x01 \x02(\x0b\x32\x12.messages.Document\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"5\n\x15\x44ocumentStoreResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB \n\x1eru.nicetu.integration.messages')




_DOCUMENT = descriptor.Descriptor(
  name='Document',
  full_name='messages.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.Document.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='title', full_name='messages.Document.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='orderNumber', full_name='messages.Document.orderNumber', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='date', full_name='messages.Document.date', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signedBy', full_name='messages.Document.signedBy', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cipher', full_name='messages.Document.cipher', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='image', full_name='messages.Document.image', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='messages.Document.type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=172,
)


_DOCUMENTGETREQUEST = descriptor.Descriptor(
  name='DocumentGetRequest',
  full_name='messages.DocumentGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.DocumentGetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='messages.DocumentGetRequest.startTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='messages.DocumentGetRequest.endTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startDate', full_name='messages.DocumentGetRequest.startDate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endDate', full_name='messages.DocumentGetRequest.endDate', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='criteria', full_name='messages.DocumentGetRequest.criteria', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.DocumentGetRequest.transactionId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initDependent', full_name='messages.DocumentGetRequest.initDependent', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=175,
  serialized_end=363,
)


_DOCUMENTGETRESPONSE = descriptor.Descriptor(
  name='DocumentGetResponse',
  full_name='messages.DocumentGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='messages.DocumentGetResponse.values', index=0,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.DocumentGetResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=365,
  serialized_end=440,
)


_DOCUMENTREMOVEREQUEST = descriptor.Descriptor(
  name='DocumentRemoveRequest',
  full_name='messages.DocumentRemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.DocumentRemoveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.DocumentRemoveRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=442,
  serialized_end=500,
)


_DOCUMENTREMOVERESPONSE = descriptor.Descriptor(
  name='DocumentRemoveResponse',
  full_name='messages.DocumentRemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.DocumentRemoveResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.DocumentRemoveResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=502,
  serialized_end=556,
)


_DOCUMENTSTOREREQUEST = descriptor.Descriptor(
  name='DocumentStoreRequest',
  full_name='messages.DocumentStoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.DocumentStoreRequest.value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.DocumentStoreRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=558,
  serialized_end=638,
)


_DOCUMENTSTORERESPONSE = descriptor.Descriptor(
  name='DocumentStoreResponse',
  full_name='messages.DocumentStoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.DocumentStoreResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.DocumentStoreResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=640,
  serialized_end=693,
)

_DOCUMENTGETREQUEST.fields_by_name['criteria'].message_type = _DOCUMENT
_DOCUMENTGETRESPONSE.fields_by_name['values'].message_type = _DOCUMENT
_DOCUMENTSTOREREQUEST.fields_by_name['value'].message_type = _DOCUMENT
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['DocumentGetRequest'] = _DOCUMENTGETREQUEST
DESCRIPTOR.message_types_by_name['DocumentGetResponse'] = _DOCUMENTGETRESPONSE
DESCRIPTOR.message_types_by_name['DocumentRemoveRequest'] = _DOCUMENTREMOVEREQUEST
DESCRIPTOR.message_types_by_name['DocumentRemoveResponse'] = _DOCUMENTREMOVERESPONSE
DESCRIPTOR.message_types_by_name['DocumentStoreRequest'] = _DOCUMENTSTOREREQUEST
DESCRIPTOR.message_types_by_name['DocumentStoreResponse'] = _DOCUMENTSTORERESPONSE

class Document(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENT
  
  # @@protoc_insertion_point(class_scope:messages.Document)

class DocumentGetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTGETREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.DocumentGetRequest)

class DocumentGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.DocumentGetResponse)

class DocumentRemoveRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTREMOVEREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.DocumentRemoveRequest)

class DocumentRemoveResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTREMOVERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.DocumentRemoveResponse)

class DocumentStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTSTOREREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.DocumentStoreRequest)

class DocumentStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DOCUMENTSTORERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.DocumentStoreResponse)

# @@protoc_insertion_point(module_scope)
