# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='LaunchContentMessages.proto',
  package='messages',
  serialized_pb='\n\x1bLaunchContentMessages.proto\x12\x08messages\"\xa6\x02\n\rLaunchContent\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12\x14\n\x0cspacecraftId\x18\x03 \x01(\x03\x12\x16\n\x0espacecraftName\x18\x04 \x01(\t\x12\x15\n\rappointmentId\x18\x05 \x01(\x03\x12\x11\n\tcountryId\x18\x06 \x01(\x03\x12\x0f\n\x07ownedId\x18\x07 \x01(\x03\x12\x0c\n\x04note\x18\x08 \x01(\t\x12\x12\n\nrecordType\x18\t \x01(\t\x12\x11\n\tinputTime\x18\n \x01(\x04\x12\x1c\n\x14preparationStartTime\x18\x0b \x01(\x04\x12\x0c\n\x04uuid\x18\x0c \x01(\t\x12\r\n\x05index\x18\r \x01(\x05\x12\x1e\n\x16launchHistoryElementId\x18\x0e \x01(\x03\"\xc6\x01\n\x17LaunchContentGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tstartTime\x18\x02 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\x04\x12\x11\n\tstartDate\x18\x04 \x01(\x04\x12\x0f\n\x07\x65ndDate\x18\x05 \x01(\x04\x12)\n\x08\x63riteria\x18\x06 \x01(\x0b\x32\x17.messages.LaunchContent\x12\x15\n\rtransactionId\x18\x07 \x01(\t\x12\x15\n\rinitDependent\x18\x08 \x01(\x08\"U\n\x18LaunchContentGetResponse\x12\'\n\x06values\x18\x08 \x03(\x0b\x32\x17.messages.LaunchContent\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"?\n\x1aLaunchContentRemoveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rtransactionId\x18\x02 \x01(\t\";\n\x1bLaunchContentRemoveResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"Z\n\x19LaunchContentStoreRequest\x12&\n\x05value\x18\x01 \x02(\x0b\x32\x17.messages.LaunchContent\x12\x15\n\rtransactionId\x18\x02 \x01(\t\":\n\x1aLaunchContentStoreResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB \n\x1eru.nicetu.integration.messages')




_LAUNCHCONTENT = descriptor.Descriptor(
  name='LaunchContent',
  full_name='messages.LaunchContent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchContent.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='priority', full_name='messages.LaunchContent.priority', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='spacecraftId', full_name='messages.LaunchContent.spacecraftId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='spacecraftName', full_name='messages.LaunchContent.spacecraftName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='appointmentId', full_name='messages.LaunchContent.appointmentId', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='countryId', full_name='messages.LaunchContent.countryId', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ownedId', full_name='messages.LaunchContent.ownedId', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='note', full_name='messages.LaunchContent.note', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='recordType', full_name='messages.LaunchContent.recordType', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inputTime', full_name='messages.LaunchContent.inputTime', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='preparationStartTime', full_name='messages.LaunchContent.preparationStartTime', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='uuid', full_name='messages.LaunchContent.uuid', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='index', full_name='messages.LaunchContent.index', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='launchHistoryElementId', full_name='messages.LaunchContent.launchHistoryElementId', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=336,
)


_LAUNCHCONTENTGETREQUEST = descriptor.Descriptor(
  name='LaunchContentGetRequest',
  full_name='messages.LaunchContentGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchContentGetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='messages.LaunchContentGetRequest.startTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='messages.LaunchContentGetRequest.endTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startDate', full_name='messages.LaunchContentGetRequest.startDate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endDate', full_name='messages.LaunchContentGetRequest.endDate', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='criteria', full_name='messages.LaunchContentGetRequest.criteria', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.LaunchContentGetRequest.transactionId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initDependent', full_name='messages.LaunchContentGetRequest.initDependent', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=339,
  serialized_end=537,
)


_LAUNCHCONTENTGETRESPONSE = descriptor.Descriptor(
  name='LaunchContentGetResponse',
  full_name='messages.LaunchContentGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='messages.LaunchContentGetResponse.values', index=0,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.LaunchContentGetResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=539,
  serialized_end=624,
)


_LAUNCHCONTENTREMOVEREQUEST = descriptor.Descriptor(
  name='LaunchContentRemoveRequest',
  full_name='messages.LaunchContentRemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchContentRemoveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.LaunchContentRemoveRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=626,
  serialized_end=689,
)


_LAUNCHCONTENTREMOVERESPONSE = descriptor.Descriptor(
  name='LaunchContentRemoveResponse',
  full_name='messages.LaunchContentRemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchContentRemoveResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.LaunchContentRemoveResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=691,
  serialized_end=750,
)


_LAUNCHCONTENTSTOREREQUEST = descriptor.Descriptor(
  name='LaunchContentStoreRequest',
  full_name='messages.LaunchContentStoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.LaunchContentStoreRequest.value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.LaunchContentStoreRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=752,
  serialized_end=842,
)


_LAUNCHCONTENTSTORERESPONSE = descriptor.Descriptor(
  name='LaunchContentStoreResponse',
  full_name='messages.LaunchContentStoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchContentStoreResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.LaunchContentStoreResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=844,
  serialized_end=902,
)

_LAUNCHCONTENTGETREQUEST.fields_by_name['criteria'].message_type = _LAUNCHCONTENT
_LAUNCHCONTENTGETRESPONSE.fields_by_name['values'].message_type = _LAUNCHCONTENT
_LAUNCHCONTENTSTOREREQUEST.fields_by_name['value'].message_type = _LAUNCHCONTENT
DESCRIPTOR.message_types_by_name['LaunchContent'] = _LAUNCHCONTENT
DESCRIPTOR.message_types_by_name['LaunchContentGetRequest'] = _LAUNCHCONTENTGETREQUEST
DESCRIPTOR.message_types_by_name['LaunchContentGetResponse'] = _LAUNCHCONTENTGETRESPONSE
DESCRIPTOR.message_types_by_name['LaunchContentRemoveRequest'] = _LAUNCHCONTENTREMOVEREQUEST
DESCRIPTOR.message_types_by_name['LaunchContentRemoveResponse'] = _LAUNCHCONTENTREMOVERESPONSE
DESCRIPTOR.message_types_by_name['LaunchContentStoreRequest'] = _LAUNCHCONTENTSTOREREQUEST
DESCRIPTOR.message_types_by_name['LaunchContentStoreResponse'] = _LAUNCHCONTENTSTORERESPONSE

class LaunchContent(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHCONTENT
  
  # @@protoc_insertion_point(class_scope:messages.LaunchContent)

class LaunchContentGetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHCONTENTGETREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.LaunchContentGetRequest)

class LaunchContentGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHCONTENTGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.LaunchContentGetResponse)

class LaunchContentRemoveRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHCONTENTREMOVEREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.LaunchContentRemoveRequest)

class LaunchContentRemoveResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHCONTENTREMOVERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.LaunchContentRemoveResponse)

class LaunchContentStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHCONTENTSTOREREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.LaunchContentStoreRequest)

class LaunchContentStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHCONTENTSTORERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.LaunchContentStoreResponse)

# @@protoc_insertion_point(module_scope)
