# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='LaunchHistoryElementMessages.proto',
  package='messages',
  serialized_pb='\n\"LaunchHistoryElementMessages.proto\x12\x08messages\"\xe9\x02\n\x14LaunchHistoryElement\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x19\n\x11primaryLaunchDate\x18\x02 \x01(\x04\x12\x19\n\x11reserveLaunchDate\x18\x03 \x01(\x04\x12\x1a\n\x12\x65xpectedLaunchDate\x18\x04 \x01(\x04\x12\x0f\n\x07quarter\x18\x05 \x01(\x05\x12\x11\n\tpolygonId\x18\x06 \x01(\x03\x12\x14\n\x0claunchSystem\x18\x07 \x01(\t\x12\x15\n\rtenDaysBefore\x18\x08 \x01(\x04\x12\x17\n\x0fthreeDaysBefore\x18\t \x01(\x04\x12\x0c\n\x04note\x18\n \x01(\t\x12\x12\n\ndocumentId\x18\x0b \x01(\x03\x12\x17\n\x0flaunchContentId\x18\x0c \x03(\x03\x12\x15\n\rhistoryHeadId\x18\r \x01(\x03\x12\x10\n\x08\x63\x61nceled\x18\x0e \x01(\x08\x12\x11\n\tpostponed\x18\x0f \x01(\x08\x12\x12\n\ninputStamp\x18\x10 \x01(\x04\"\xd4\x01\n\x1eLaunchHistoryElementGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tstartTime\x18\x02 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\x04\x12\x11\n\tstartDate\x18\x04 \x01(\x04\x12\x0f\n\x07\x65ndDate\x18\x05 \x01(\x04\x12\x30\n\x08\x63riteria\x18\x06 \x01(\x0b\x32\x1e.messages.LaunchHistoryElement\x12\x15\n\rtransactionId\x18\x07 \x01(\t\x12\x15\n\rinitDependent\x18\x08 \x01(\x08\"c\n\x1fLaunchHistoryElementGetResponse\x12.\n\x06values\x18\x08 \x03(\x0b\x32\x1e.messages.LaunchHistoryElement\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"F\n!LaunchHistoryElementRemoveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"B\n\"LaunchHistoryElementRemoveResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"h\n LaunchHistoryElementStoreRequest\x12-\n\x05value\x18\x01 \x02(\x0b\x32\x1e.messages.LaunchHistoryElement\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"A\n!LaunchHistoryElementStoreResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB \n\x1eru.nicetu.integration.messages')




_LAUNCHHISTORYELEMENT = descriptor.Descriptor(
  name='LaunchHistoryElement',
  full_name='messages.LaunchHistoryElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchHistoryElement.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='primaryLaunchDate', full_name='messages.LaunchHistoryElement.primaryLaunchDate', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reserveLaunchDate', full_name='messages.LaunchHistoryElement.reserveLaunchDate', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expectedLaunchDate', full_name='messages.LaunchHistoryElement.expectedLaunchDate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='quarter', full_name='messages.LaunchHistoryElement.quarter', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='polygonId', full_name='messages.LaunchHistoryElement.polygonId', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='launchSystem', full_name='messages.LaunchHistoryElement.launchSystem', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tenDaysBefore', full_name='messages.LaunchHistoryElement.tenDaysBefore', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='threeDaysBefore', full_name='messages.LaunchHistoryElement.threeDaysBefore', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='note', full_name='messages.LaunchHistoryElement.note', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='documentId', full_name='messages.LaunchHistoryElement.documentId', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='launchContentId', full_name='messages.LaunchHistoryElement.launchContentId', index=11,
      number=12, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='historyHeadId', full_name='messages.LaunchHistoryElement.historyHeadId', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='canceled', full_name='messages.LaunchHistoryElement.canceled', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='postponed', full_name='messages.LaunchHistoryElement.postponed', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inputStamp', full_name='messages.LaunchHistoryElement.inputStamp', index=15,
      number=16, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=410,
)


_LAUNCHHISTORYELEMENTGETREQUEST = descriptor.Descriptor(
  name='LaunchHistoryElementGetRequest',
  full_name='messages.LaunchHistoryElementGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchHistoryElementGetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='messages.LaunchHistoryElementGetRequest.startTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='messages.LaunchHistoryElementGetRequest.endTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startDate', full_name='messages.LaunchHistoryElementGetRequest.startDate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endDate', full_name='messages.LaunchHistoryElementGetRequest.endDate', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='criteria', full_name='messages.LaunchHistoryElementGetRequest.criteria', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.LaunchHistoryElementGetRequest.transactionId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initDependent', full_name='messages.LaunchHistoryElementGetRequest.initDependent', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=413,
  serialized_end=625,
)


_LAUNCHHISTORYELEMENTGETRESPONSE = descriptor.Descriptor(
  name='LaunchHistoryElementGetResponse',
  full_name='messages.LaunchHistoryElementGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='messages.LaunchHistoryElementGetResponse.values', index=0,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.LaunchHistoryElementGetResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=627,
  serialized_end=726,
)


_LAUNCHHISTORYELEMENTREMOVEREQUEST = descriptor.Descriptor(
  name='LaunchHistoryElementRemoveRequest',
  full_name='messages.LaunchHistoryElementRemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchHistoryElementRemoveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.LaunchHistoryElementRemoveRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=728,
  serialized_end=798,
)


_LAUNCHHISTORYELEMENTREMOVERESPONSE = descriptor.Descriptor(
  name='LaunchHistoryElementRemoveResponse',
  full_name='messages.LaunchHistoryElementRemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchHistoryElementRemoveResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.LaunchHistoryElementRemoveResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=800,
  serialized_end=866,
)


_LAUNCHHISTORYELEMENTSTOREREQUEST = descriptor.Descriptor(
  name='LaunchHistoryElementStoreRequest',
  full_name='messages.LaunchHistoryElementStoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.LaunchHistoryElementStoreRequest.value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.LaunchHistoryElementStoreRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=868,
  serialized_end=972,
)


_LAUNCHHISTORYELEMENTSTORERESPONSE = descriptor.Descriptor(
  name='LaunchHistoryElementStoreResponse',
  full_name='messages.LaunchHistoryElementStoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.LaunchHistoryElementStoreResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.LaunchHistoryElementStoreResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=974,
  serialized_end=1039,
)

_LAUNCHHISTORYELEMENTGETREQUEST.fields_by_name['criteria'].message_type = _LAUNCHHISTORYELEMENT
_LAUNCHHISTORYELEMENTGETRESPONSE.fields_by_name['values'].message_type = _LAUNCHHISTORYELEMENT
_LAUNCHHISTORYELEMENTSTOREREQUEST.fields_by_name['value'].message_type = _LAUNCHHISTORYELEMENT
DESCRIPTOR.message_types_by_name['LaunchHistoryElement'] = _LAUNCHHISTORYELEMENT
DESCRIPTOR.message_types_by_name['LaunchHistoryElementGetRequest'] = _LAUNCHHISTORYELEMENTGETREQUEST
DESCRIPTOR.message_types_by_name['LaunchHistoryElementGetResponse'] = _LAUNCHHISTORYELEMENTGETRESPONSE
DESCRIPTOR.message_types_by_name['LaunchHistoryElementRemoveRequest'] = _LAUNCHHISTORYELEMENTREMOVEREQUEST
DESCRIPTOR.message_types_by_name['LaunchHistoryElementRemoveResponse'] = _LAUNCHHISTORYELEMENTREMOVERESPONSE
DESCRIPTOR.message_types_by_name['LaunchHistoryElementStoreRequest'] = _LAUNCHHISTORYELEMENTSTOREREQUEST
DESCRIPTOR.message_types_by_name['LaunchHistoryElementStoreResponse'] = _LAUNCHHISTORYELEMENTSTORERESPONSE

class LaunchHistoryElement(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHHISTORYELEMENT
  
  # @@protoc_insertion_point(class_scope:messages.LaunchHistoryElement)

class LaunchHistoryElementGetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHHISTORYELEMENTGETREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.LaunchHistoryElementGetRequest)

class LaunchHistoryElementGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHHISTORYELEMENTGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.LaunchHistoryElementGetResponse)

class LaunchHistoryElementRemoveRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHHISTORYELEMENTREMOVEREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.LaunchHistoryElementRemoveRequest)

class LaunchHistoryElementRemoveResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHHISTORYELEMENTREMOVERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.LaunchHistoryElementRemoveResponse)

class LaunchHistoryElementStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHHISTORYELEMENTSTOREREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.LaunchHistoryElementStoreRequest)

class LaunchHistoryElementStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LAUNCHHISTORYELEMENTSTORERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.LaunchHistoryElementStoreResponse)

# @@protoc_insertion_point(module_scope)
