# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='ProgramMessages.proto',
  package='messages',
  serialized_pb='\n\x15ProgramMessages.proto\x12\x08messages\"\x96\x01\n\x07Program\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tshortName\x18\x02 \x01(\t\x12\x10\n\x08\x66ullName\x18\x03 \x01(\t\x12\x14\n\x0ctrainingType\x18\x04 \x01(\t\x12\x11\n\tstartTime\x18\x05 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x06 \x01(\x04\x12\x12\n\ndocumentId\x18\x07 \x01(\x03\x12\x0c\n\x04note\x18\x08 \x01(\t\"\xba\x01\n\x11ProgramGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tstartTime\x18\x02 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\x04\x12\x11\n\tstartDate\x18\x04 \x01(\x04\x12\x0f\n\x07\x65ndDate\x18\x05 \x01(\x04\x12#\n\x08\x63riteria\x18\x06 \x01(\x0b\x32\x11.messages.Program\x12\x15\n\rtransactionId\x18\x07 \x01(\t\x12\x15\n\rinitDependent\x18\x08 \x01(\x08\"I\n\x12ProgramGetResponse\x12!\n\x06values\x18\x08 \x03(\x0b\x32\x11.messages.Program\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"9\n\x14ProgramRemoveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"5\n\x15ProgramRemoveResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"N\n\x13ProgramStoreRequest\x12 \n\x05value\x18\x01 \x02(\x0b\x32\x11.messages.Program\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"4\n\x14ProgramStoreResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB \n\x1eru.nicetu.integration.messages')




_PROGRAM = descriptor.Descriptor(
  name='Program',
  full_name='messages.Program',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.Program.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shortName', full_name='messages.Program.shortName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fullName', full_name='messages.Program.fullName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='trainingType', full_name='messages.Program.trainingType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='messages.Program.startTime', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='messages.Program.endTime', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='documentId', full_name='messages.Program.documentId', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='note', full_name='messages.Program.note', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=186,
)


_PROGRAMGETREQUEST = descriptor.Descriptor(
  name='ProgramGetRequest',
  full_name='messages.ProgramGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.ProgramGetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='messages.ProgramGetRequest.startTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='messages.ProgramGetRequest.endTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startDate', full_name='messages.ProgramGetRequest.startDate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endDate', full_name='messages.ProgramGetRequest.endDate', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='criteria', full_name='messages.ProgramGetRequest.criteria', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.ProgramGetRequest.transactionId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initDependent', full_name='messages.ProgramGetRequest.initDependent', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=189,
  serialized_end=375,
)


_PROGRAMGETRESPONSE = descriptor.Descriptor(
  name='ProgramGetResponse',
  full_name='messages.ProgramGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='messages.ProgramGetResponse.values', index=0,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.ProgramGetResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=377,
  serialized_end=450,
)


_PROGRAMREMOVEREQUEST = descriptor.Descriptor(
  name='ProgramRemoveRequest',
  full_name='messages.ProgramRemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.ProgramRemoveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.ProgramRemoveRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=452,
  serialized_end=509,
)


_PROGRAMREMOVERESPONSE = descriptor.Descriptor(
  name='ProgramRemoveResponse',
  full_name='messages.ProgramRemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.ProgramRemoveResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.ProgramRemoveResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=511,
  serialized_end=564,
)


_PROGRAMSTOREREQUEST = descriptor.Descriptor(
  name='ProgramStoreRequest',
  full_name='messages.ProgramStoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.ProgramStoreRequest.value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.ProgramStoreRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=566,
  serialized_end=644,
)


_PROGRAMSTORERESPONSE = descriptor.Descriptor(
  name='ProgramStoreResponse',
  full_name='messages.ProgramStoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.ProgramStoreResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.ProgramStoreResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=646,
  serialized_end=698,
)

_PROGRAMGETREQUEST.fields_by_name['criteria'].message_type = _PROGRAM
_PROGRAMGETRESPONSE.fields_by_name['values'].message_type = _PROGRAM
_PROGRAMSTOREREQUEST.fields_by_name['value'].message_type = _PROGRAM
DESCRIPTOR.message_types_by_name['Program'] = _PROGRAM
DESCRIPTOR.message_types_by_name['ProgramGetRequest'] = _PROGRAMGETREQUEST
DESCRIPTOR.message_types_by_name['ProgramGetResponse'] = _PROGRAMGETRESPONSE
DESCRIPTOR.message_types_by_name['ProgramRemoveRequest'] = _PROGRAMREMOVEREQUEST
DESCRIPTOR.message_types_by_name['ProgramRemoveResponse'] = _PROGRAMREMOVERESPONSE
DESCRIPTOR.message_types_by_name['ProgramStoreRequest'] = _PROGRAMSTOREREQUEST
DESCRIPTOR.message_types_by_name['ProgramStoreResponse'] = _PROGRAMSTORERESPONSE

class Program(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAM
  
  # @@protoc_insertion_point(class_scope:messages.Program)

class ProgramGetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAMGETREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.ProgramGetRequest)

class ProgramGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAMGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.ProgramGetResponse)

class ProgramRemoveRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAMREMOVEREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.ProgramRemoveRequest)

class ProgramRemoveResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAMREMOVERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.ProgramRemoveResponse)

class ProgramStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAMSTOREREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.ProgramStoreRequest)

class ProgramStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAMSTORERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.ProgramStoreResponse)

# @@protoc_insertion_point(module_scope)
