# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='RequestSerial.proto',
  package='messages',
  serialized_pb='\n\x13RequestSerial.proto\x12\x08messages\".\n\tMsgHeader\x12\x10\n\x08msgClass\x18\x01 \x02(\t\x12\x0f\n\x07msgSize\x18\x02 \x02(\x05\x42/\n\x1eru.nicetu.integration.messagesB\rRequestSerial')




_MSGHEADER = descriptor.Descriptor(
  name='MsgHeader',
  full_name='messages.MsgHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='msgClass', full_name='messages.MsgHeader.msgClass', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msgSize', full_name='messages.MsgHeader.msgSize', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['MsgHeader'] = _MSGHEADER

class MsgHeader(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSGHEADER
  
  # @@protoc_insertion_point(class_scope:messages.MsgHeader)

# @@protoc_insertion_point(module_scope)
