# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='SpacecraftAppointmentMessages.proto',
  package='messages',
  serialized_pb='\n#SpacecraftAppointmentMessages.proto\x12\x08messages\"F\n\x15SpacecraftAppointment\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0b\x61ppointment\x18\x02 \x01(\t\x12\x0c\n\x04note\x18\x03 \x01(\t\"\xd6\x01\n\x1fSpacecraftAppointmentGetRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tstartTime\x18\x02 \x01(\x04\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\x04\x12\x11\n\tstartDate\x18\x04 \x01(\x04\x12\x0f\n\x07\x65ndDate\x18\x05 \x01(\x04\x12\x31\n\x08\x63riteria\x18\x06 \x01(\x0b\x32\x1f.messages.SpacecraftAppointment\x12\x15\n\rtransactionId\x18\x07 \x01(\t\x12\x15\n\rinitDependent\x18\x08 \x01(\x08\"e\n SpacecraftAppointmentGetResponse\x12/\n\x06values\x18\x08 \x03(\x0b\x32\x1f.messages.SpacecraftAppointment\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"G\n\"SpacecraftAppointmentRemoveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"C\n#SpacecraftAppointmentRemoveResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\t\"j\n!SpacecraftAppointmentStoreRequest\x12.\n\x05value\x18\x01 \x02(\x0b\x32\x1f.messages.SpacecraftAppointment\x12\x15\n\rtransactionId\x18\x02 \x01(\t\"B\n\"SpacecraftAppointmentStoreResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08\x65rrorMsg\x18\x02 \x01(\tB \n\x1eru.nicetu.integration.messages')




_SPACECRAFTAPPOINTMENT = descriptor.Descriptor(
  name='SpacecraftAppointment',
  full_name='messages.SpacecraftAppointment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.SpacecraftAppointment.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='appointment', full_name='messages.SpacecraftAppointment.appointment', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='note', full_name='messages.SpacecraftAppointment.note', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=119,
)


_SPACECRAFTAPPOINTMENTGETREQUEST = descriptor.Descriptor(
  name='SpacecraftAppointmentGetRequest',
  full_name='messages.SpacecraftAppointmentGetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.SpacecraftAppointmentGetRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startTime', full_name='messages.SpacecraftAppointmentGetRequest.startTime', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endTime', full_name='messages.SpacecraftAppointmentGetRequest.endTime', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='startDate', full_name='messages.SpacecraftAppointmentGetRequest.startDate', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='endDate', full_name='messages.SpacecraftAppointmentGetRequest.endDate', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='criteria', full_name='messages.SpacecraftAppointmentGetRequest.criteria', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.SpacecraftAppointmentGetRequest.transactionId', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='initDependent', full_name='messages.SpacecraftAppointmentGetRequest.initDependent', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=122,
  serialized_end=336,
)


_SPACECRAFTAPPOINTMENTGETRESPONSE = descriptor.Descriptor(
  name='SpacecraftAppointmentGetResponse',
  full_name='messages.SpacecraftAppointmentGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='values', full_name='messages.SpacecraftAppointmentGetResponse.values', index=0,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.SpacecraftAppointmentGetResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=338,
  serialized_end=439,
)


_SPACECRAFTAPPOINTMENTREMOVEREQUEST = descriptor.Descriptor(
  name='SpacecraftAppointmentRemoveRequest',
  full_name='messages.SpacecraftAppointmentRemoveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.SpacecraftAppointmentRemoveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.SpacecraftAppointmentRemoveRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=441,
  serialized_end=512,
)


_SPACECRAFTAPPOINTMENTREMOVERESPONSE = descriptor.Descriptor(
  name='SpacecraftAppointmentRemoveResponse',
  full_name='messages.SpacecraftAppointmentRemoveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.SpacecraftAppointmentRemoveResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.SpacecraftAppointmentRemoveResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=514,
  serialized_end=581,
)


_SPACECRAFTAPPOINTMENTSTOREREQUEST = descriptor.Descriptor(
  name='SpacecraftAppointmentStoreRequest',
  full_name='messages.SpacecraftAppointmentStoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='messages.SpacecraftAppointmentStoreRequest.value', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='transactionId', full_name='messages.SpacecraftAppointmentStoreRequest.transactionId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=583,
  serialized_end=689,
)


_SPACECRAFTAPPOINTMENTSTORERESPONSE = descriptor.Descriptor(
  name='SpacecraftAppointmentStoreResponse',
  full_name='messages.SpacecraftAppointmentStoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='messages.SpacecraftAppointmentStoreResponse.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='errorMsg', full_name='messages.SpacecraftAppointmentStoreResponse.errorMsg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=691,
  serialized_end=757,
)

_SPACECRAFTAPPOINTMENTGETREQUEST.fields_by_name['criteria'].message_type = _SPACECRAFTAPPOINTMENT
_SPACECRAFTAPPOINTMENTGETRESPONSE.fields_by_name['values'].message_type = _SPACECRAFTAPPOINTMENT
_SPACECRAFTAPPOINTMENTSTOREREQUEST.fields_by_name['value'].message_type = _SPACECRAFTAPPOINTMENT
DESCRIPTOR.message_types_by_name['SpacecraftAppointment'] = _SPACECRAFTAPPOINTMENT
DESCRIPTOR.message_types_by_name['SpacecraftAppointmentGetRequest'] = _SPACECRAFTAPPOINTMENTGETREQUEST
DESCRIPTOR.message_types_by_name['SpacecraftAppointmentGetResponse'] = _SPACECRAFTAPPOINTMENTGETRESPONSE
DESCRIPTOR.message_types_by_name['SpacecraftAppointmentRemoveRequest'] = _SPACECRAFTAPPOINTMENTREMOVEREQUEST
DESCRIPTOR.message_types_by_name['SpacecraftAppointmentRemoveResponse'] = _SPACECRAFTAPPOINTMENTREMOVERESPONSE
DESCRIPTOR.message_types_by_name['SpacecraftAppointmentStoreRequest'] = _SPACECRAFTAPPOINTMENTSTOREREQUEST
DESCRIPTOR.message_types_by_name['SpacecraftAppointmentStoreResponse'] = _SPACECRAFTAPPOINTMENTSTORERESPONSE

class SpacecraftAppointment(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPACECRAFTAPPOINTMENT
  
  # @@protoc_insertion_point(class_scope:messages.SpacecraftAppointment)

class SpacecraftAppointmentGetRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPACECRAFTAPPOINTMENTGETREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.SpacecraftAppointmentGetRequest)

class SpacecraftAppointmentGetResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPACECRAFTAPPOINTMENTGETRESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.SpacecraftAppointmentGetResponse)

class SpacecraftAppointmentRemoveRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPACECRAFTAPPOINTMENTREMOVEREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.SpacecraftAppointmentRemoveRequest)

class SpacecraftAppointmentRemoveResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPACECRAFTAPPOINTMENTREMOVERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.SpacecraftAppointmentRemoveResponse)

class SpacecraftAppointmentStoreRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPACECRAFTAPPOINTMENTSTOREREQUEST
  
  # @@protoc_insertion_point(class_scope:messages.SpacecraftAppointmentStoreRequest)

class SpacecraftAppointmentStoreResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPACECRAFTAPPOINTMENTSTORERESPONSE
  
  # @@protoc_insertion_point(class_scope:messages.SpacecraftAppointmentStoreResponse)

# @@protoc_insertion_point(module_scope)
